# Site settings
name: quadbeats
email: email
url: url
description: "A blog and a portfolio"
author: "author"
title: "조성규"
permalink: pretty
baseurl: /jekyll-theme-blogfolio

# social
github:
  username: quadbeats
